export const Types = {
    GET_DETAIL: 'GET_DETAIL',
    SET_LINK: 'SET_LINK',
    ADD_TO_CART: 'ADD_TO_CART',
    GLOBAL_QUANTITY: 'GLOBAL_QUANTITY',
    RESTART_QUANTITY: 'RESTART_QUANTITY',
    RESTART_SHOP: 'RESTART_SHOP',
    UPDATE_CART: 'UPDATE_CART',
    UPDATE_GLOBAL_QUANTITY: 'UPDATE_GLOBAL_QUANTITY',
    ERASE_ELEMENT: 'ERASE_ELEMENT',
}